name: auto_repair_shop
description: "Auto Repair Shop – Mobile App (CU01, CU02, CU03, CU06)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP client
  dio: ^5.4.0

  # Firebase (Push Notifications)
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^18.0.0

  # Environment variables
  flutter_dotenv: ^5.1.0

  # Local storage
  shared_preferences: ^2.2.2

  # State management
  provider: ^6.1.2

  # Google Fonts (Inter)
  google_fonts: ^6.2.1

  # Map & location
  flutter_map: ^8.1.0
  flutter_map_location_marker: ^10.2.0
  latlong2: ^0.9.0
  geolocator: ^14.0.0

  # Media & file handling
  image_picker: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.1.0
  record: ^6.0.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
